---
- name: Provision a vagrant machine
  hosts: localhost
  vars:
    box: "ubuntu/trusty64"
  tasks:
    - name: create a Vagrantfile
      command: vagrant init {{ box }} creates=Vagrantfile

    - name: Bringing up a vagrant server
      command: vagrant up

    - name: add teh Vagrant hosts to the inventory
      add_host: >
        name=vagrant
        ansible_ssh_host=127.0.0.1
        ansible_ssh_port=222
        ansible_ssh_user=vagrant
        ansible_ssh_private_key=/home/alex/.vagrant.d/insecure_private_key